const clubNames: Record<string, string> = {
  Liverpool: '利物浦', 'Newcastle United': '纽卡斯尔联', 'Borussia Dortmund': '多特蒙德', 'Real Sociedad': '皇家社会',
  'Manchester City': '曼城', 'Manchester United': '曼联', Chelsea: '切尔西', 'Chelsea FC': '切尔西',
  Arsenal: '阿森纳', 'Arsenal FC': '阿森纳',
  'Tottenham Hotspur': '托特纳姆热刺', 'Real Madrid': '皇家马德里', 'FC Barcelona': '巴塞罗那',
  'Paris Saint-Germain': '巴黎圣日耳曼', 'Bayern Munich': '拜仁慕尼黑', 'Bayer Leverkusen': '勒沃库森',
  'AC Milan': 'AC 米兰', 'Inter Milan': '国际米兰', Juventus: '尤文图斯', Napoli: '那不勒斯',
  'AS Roma': '罗马', 'Atletico Madrid': '马德里竞技', 'RB Leipzig': '莱比锡', Ajax: '阿贾克斯',
  'Atlético': '马德里竞技',
  Benfica: '本菲卡', 'FC Porto': '波尔图', 'Sporting Lisbon': '葡萄牙体育', Monaco: '摩纳哥',
  'Olympique Lyonnais': '里昂', Marseille: '马赛', Sevilla: '塞维利亚', Valencia: '瓦伦西亚',
  Villarreal: '比利亚雷亚尔', 'Athletic Bilbao': '毕尔巴鄂竞技', 'Real Betis Balompié': '皇家贝蒂斯',
  'Inter Miami': '迈阿密国际',
  Celtic: '凯尔特人', Southampton: '南安普顿', 'FC Schalke 04': '沙尔克 04',
  Everton: '埃弗顿', 'West Ham United': '西汉姆联', 'Leicester City': '莱斯特城',
  Fiorentina: '佛罗伦萨', Atalanta: '亚特兰大', 'Lazio': '拉齐奥',
  Barcelona: '巴塞罗那', 'Barça Atlètic': '巴塞罗那竞技', Parma: '帕尔马',
  'B. Leverkusen': '勒沃库森', Besiktas: '贝西克塔斯', 'CSKA Moscow': '莫斯科中央陆军',
  'Emirates Club': '酋长俱乐部', 'FC Metz': '梅斯', Fluminense: '弗鲁米嫩塞', Gimnastic: '塔拉戈纳体操',
  Independiente: '独立竞技', 'LOSC Lille': '里尔', Lille: '里尔', Lecce: '莱切', Lens: '朗斯',
  'Los Angeles FC': '洛杉矶 FC', Lyon: '里昂', 'Olympique Lyon': '里昂',
  'Man Utd': '曼联', Olympiacos: '奥林匹亚科斯', 'Orlando City': '奥兰多城',
  'River Plate': '河床', Roma: '罗马', 'Sao Paulo': '圣保罗', 'Sharjah FC': '沙迦',
  'Vissel Kobe': '神户胜利船',
  AIK: 'AIK 索尔纳', Dortmund: '多特蒙德', Newcastle: '纽卡斯尔联', 'Willem II': '威廉二世',
  Santos: '桑托斯', 'New York Cosmos': '纽约宇宙', Figueirense: '费古埃伦斯',
  'TSG 1899 Hoffenheim': '霍芬海姆', 'Al-Ahli': '吉达国民', 'Al-Sadd': '萨德',
  Pescara: '佩斯卡拉', 'Al-Arabi': '阿拉比', 'Al-Duhail': '杜海勒', Cavese: '卡维塞',
  Foggia: '福贾', 'Toronto FC': '多伦多 FC',
}

export const formatClubName = (name: string) => clubNames[name] ?? name
