export type Player = {
  slug: string
  name: string
  zh: string
  aliases: string[]
  nation: string
  flag: string
  position: string
  years: string
  number: number
  kicker: string
  intro: string
  clues: string[]
  timeline: { year: string; title: string; text: string }[]
  honors: string[]
  match: string
  fact: string
  image: string
  credit: string
}

const commons = (file: string) => `https://commons.wikimedia.org/wiki/Special:FilePath/${encodeURIComponent(file)}?width=1000`

export const players: Player[] = [
  {
    slug: 'lionel-messi', name: 'Lionel Messi', zh: '梅西', aliases: ['里奥梅西', '莱昂内尔梅西', 'messi'], nation: '阿根廷', flag: '🇦🇷', position: '右边锋 / 前腰', years: '2004—至今', number: 10,
    kicker: '把足球变成贴着左脚运行的艺术', intro: '从拉玛西亚的瘦小少年，到带领阿根廷登上世界之巅。梅西以极低重心的连续触球、穿透防线的传球和冷静终结，重新定义了现代进攻核心。',
    clues: ['我出生在南美，却在欧洲完成青训。', '我的职业生涯与 10 号球衣紧密相连。', '我曾在同一家俱乐部赢得四次欧冠。', '我的惯用脚是左脚，以低重心盘带闻名。', '2022 年，我举起了此前唯一缺少的重要奖杯。'],
    timeline: [{ year: '2004', title: '巴萨一线队首秀', text: '17 岁完成正式比赛首秀。' }, { year: '2009', title: '首夺金球奖', text: '三冠王赛季成为世界最佳。' }, { year: '2012', title: '年度 91 球', text: '刷新自然年进球纪录。' }, { year: '2021', title: '美洲杯登顶', text: '赢得成年国家队首座大赛冠军。' }, { year: '2022', title: '加冕世界杯', text: '在卡塔尔完成国家队生涯巅峰。' }],
    honors: ['世界杯冠军', '8× 金球奖', '4× 欧冠冠军', '美洲杯冠军'], match: '2022 世界杯决赛 · 阿根廷 vs 法国', fact: '他在巴塞罗那正式比赛打入 672 球，是单一俱乐部进球纪录保持者。', image: commons('Lionel-Messi-Argentina-2022-FIFA-World-Cup.jpg'), credit: 'Wikimedia Commons · CC licensed'
  },
  { slug:'cristiano-ronaldo', name:'Cristiano Ronaldo', zh:'C 罗', aliases:['c罗纳尔多','克里斯蒂亚诺罗纳尔多','ronaldo','cr7'], nation:'葡萄牙', flag:'🇵🇹', position:'左边锋 / 中锋', years:'2002—至今', number:7, kicker:'用极致自律不断改写进球边界', intro:'从马德拉岛走出的边锋，逐渐进化为足球史上最高产的终结者之一。爆发力、头球、无球跑位与长期稳定性构成了他的标志。', clues:['我来自欧洲伊比利亚半岛。','7 号是我最具辨识度的号码。','我在英格兰、西班牙和意大利都赢得过联赛冠军。','我以弹跳、头球和逆足终结闻名。','我是葡萄牙国家队历史上的代表人物。'], timeline:[{year:'2003',title:'登陆曼联',text:'从葡萄牙体育加盟英超。'},{year:'2008',title:'首夺金球',text:'帮助曼联赢得欧冠。'},{year:'2009',title:'转会皇马',text:'开启队史最高产阶段。'},{year:'2016',title:'欧洲杯冠军',text:'葡萄牙首夺欧洲杯。'},{year:'2018',title:'转战意甲',text:'加盟尤文图斯。'}], honors:['5× 金球奖','5× 欧冠冠军','欧洲杯冠军','欧国联冠军'], match:'2018 欧冠 · 皇家马德里 vs 尤文图斯', fact:'他的职业生涯正式比赛进球跨越了多个时代。', image:commons('Cristiano Ronaldo 2018.jpg'), credit:'Wikimedia Commons · CC BY-SA' },
  { slug:'diego-maradona', name:'Diego Maradona', zh:'马拉多纳', aliases:['迭戈马拉多纳','maradona'], nation:'阿根廷', flag:'🇦🇷', position:'前腰 / 影锋', years:'1976—1997', number:10, kicker:'一个人扛着整支球队穿越时代', intro:'兼具街头想象力与惊人对抗能力的左脚大师。他在 1986 年世界杯留下足球史上最浓烈、也最矛盾的一段个人英雄叙事。', clues:['我是一名已经退役的南美 10 号。','我曾让一座意大利南部城市疯狂。','我的左脚和强壮下盘是标志。','一场比赛里，我留下两个完全不同的著名进球。','1986 年世界杯属于我。'], timeline:[{year:'1976',title:'职业首秀',text:'15 岁亮相阿根廷顶级联赛。'},{year:'1982',title:'加盟巴萨',text:'首次登陆欧洲足坛。'},{year:'1984',title:'那不勒斯时代',text:'带领球队两夺意甲。'},{year:'1986',title:'世界杯封王',text:'以队长身份率阿根廷夺冠。'},{year:'1997',title:'结束球员生涯',text:'在博卡青年退役。'}], honors:['世界杯冠军','2× 意甲冠军','联盟杯冠军'], match:'1986 世界杯 · 阿根廷 vs 英格兰', fact:'他在那不勒斯的 10 号球衣被永久退役。', image:commons('Diego Maradona 2017.jpg'), credit:'Wikimedia Commons · CC licensed' },
  { slug:'pele', name:'Pelé', zh:'贝利', aliases:['球王贝利','pele'], nation:'巴西', flag:'🇧🇷', position:'影锋 / 中锋', years:'1956—1977', number:10, kicker:'让 10 号成为世界足球的王冠', intro:'技术全面、效率惊人且富有创造力的第一代全球足球偶像。三座世界杯冠军至今仍是独一无二的球员纪录。', clues:['我来自足球王国。','我十几岁便参加世界杯。','我的大部分俱乐部生涯留在祖国。','我帮助足球在北美扩大影响。','我是唯一三夺世界杯的球员。'], timeline:[{year:'1956',title:'桑托斯首秀',text:'15 岁开启职业生涯。'},{year:'1958',title:'少年世界冠军',text:'17 岁在决赛梅开二度。'},{year:'1962',title:'成功卫冕',text:'巴西连续两届夺冠。'},{year:'1970',title:'第三座世界杯',text:'作为核心率巴西永久保留雷米特杯。'},{year:'1977',title:'纽约告别',text:'在宇宙队结束职业生涯。'}], honors:['3× 世界杯冠军','2× 解放者杯冠军'], match:'1970 世界杯决赛 · 巴西 vs 意大利', fact:'贝利的比赛录像有限，但他的全面性远超“禁区射手”的标签。', image:commons('Pele by John Mathew Smith.jpg'), credit:'Wikimedia Commons · CC BY-SA' },
  { slug:'johan-cruyff',name:'Johan Cruyff',zh:'克鲁伊夫',aliases:['约翰克鲁伊夫','cruyff'],nation:'荷兰',flag:'🇳🇱',position:'中锋 / 前腰',years:'1964—1984',number:14,kicker:'先改变球场，再改变足球思想',intro:'全攻全守足球的场上化身。克鲁伊夫不仅以优雅转身和空间理解统治比赛，退役后更塑造了巴塞罗那的现代足球哲学。',clues:['我来自橙衣军团。','我最具代表性的号码不是 10 号。','有一种著名转身以我命名。','我在两家欧洲豪门都留下深远影响。','我代表全攻全守足球。'],timeline:[{year:'1964',title:'阿贾克斯首秀',text:'开启荷兰王朝。'},{year:'1971',title:'欧冠三连冠起点',text:'阿贾克斯统治欧洲。'},{year:'1973',title:'加盟巴萨',text:'帮助球队重夺西甲。'},{year:'1974',title:'世界杯亚军',text:'全攻全守震撼世界。'},{year:'1988',title:'执教巴萨',text:'建立梦一队基础。'}],honors:['3× 金球奖','3× 欧冠冠军','世界杯亚军'],match:'1974 世界杯 · 荷兰 vs 巴西',fact:'他坚持穿 14 号，让非传统主力号码成为传奇符号。',image:commons('Johan Cruyff 1974c.jpg'),credit:'Wikimedia Commons · public domain/CC'},
  { slug:'franz-beckenbauer',name:'Franz Beckenbauer',zh:'贝肯鲍尔',aliases:['弗朗茨贝肯鲍尔','beckenbauer','足球皇帝'],nation:'德国',flag:'🇩🇪',position:'清道夫 / 中卫',years:'1964—1983',number:5,kicker:'从后场开始优雅地统治比赛',intro:'“足球皇帝”将自由人位置提升为组织核心，以从容推进、预判和领导力重新定义后卫的上限。',clues:['我是一名欧洲传奇后卫。','我被称为皇帝。','我让自由人位置成为战术核心。','我曾效力拜仁慕尼黑。','我以球员和教练身份都赢得世界杯。'],timeline:[{year:'1964',title:'拜仁首秀',text:'开启俱乐部传奇。'},{year:'1972',title:'欧洲杯冠军',text:'率西德登顶欧洲。'},{year:'1974',title:'世界杯冠军',text:'作为队长主场夺冠。'},{year:'1976',title:'欧冠三连冠',text:'完成欧洲霸业。'},{year:'1990',title:'教练世界杯',text:'率队再次夺冠。'}],honors:['世界杯冠军','欧洲杯冠军','2× 金球奖','3× 欧冠冠军'],match:'1974 世界杯决赛 · 西德 vs 荷兰',fact:'他是极少数以球员和主教练身份都获得世界杯的人。',image:commons('Franz Beckenbauer 22-6-74.png'),credit:'Wikimedia Commons · CC licensed'},
  { slug:'zinedine-zidane',name:'Zinedine Zidane',zh:'齐达内',aliases:['齐祖','齐内丁齐达内','zidane'],nation:'法国',flag:'🇫🇷',position:'前腰',years:'1989—2006',number:10,kicker:'最拥挤的空间里仍然从容转身',intro:'以第一脚触球、马赛回旋和大赛表现著称的中场艺术家。他的职业生涯同时拥有最优雅与最戏剧性的画面。',clues:['我出生在法国南部。','我的父母来自北非。','一种回旋动作常与我联系。','我在世界杯决赛中打进过三个球。','退役后我率队实现欧冠三连冠。'],timeline:[{year:'1989',title:'戛纳首秀',text:'踏入法国职业足坛。'},{year:'1996',title:'加盟尤文',text:'成为欧洲顶级中场。'},{year:'1998',title:'世界杯冠军',text:'决赛头球梅开二度。'},{year:'2002',title:'天外飞仙',text:'欧冠决赛凌空制胜。'},{year:'2006',title:'世界杯告别',text:'以决赛结束球员生涯。'}],honors:['世界杯冠军','欧洲杯冠军','金球奖','欧冠冠军'],match:'2006 世界杯 · 法国 vs 巴西',fact:'他在皇马球员和教练时期都赢得了欧冠。',image:commons('Zinedine Zidane by Tasnim 03.jpg'),credit:'Wikimedia Commons · CC BY-SA'},
  { slug:'ronaldo-nazario',name:'Ronaldo Nazário',zh:'罗纳尔多',aliases:['大罗','外星人','罗纳尔多纳扎里奥','ronaldo nazario'],nation:'巴西',flag:'🇧🇷',position:'中锋',years:'1993—2011',number:9,kicker:'巅峰速度与技术结合的终极中锋',intro:'“外星人”把爆发启动、连续变向和门前冷静组合在一个强壮身体里。即使重伤改变轨迹，他依然完成世界杯救赎。',clues:['我是巴西 9 号。','我被称为外星人。','我效力过西班牙和意大利的多家豪门。','严重膝伤几乎终结我的生涯。','2002 年我以 8 球赢得世界杯金靴。'],timeline:[{year:'1993',title:'克鲁塞罗成名',text:'少年赛季高效进球。'},{year:'1996',title:'巴萨惊艳',text:'展示不可阻挡的突破。'},{year:'1998',title:'世界杯决赛',text:'决赛前突发状况留下悬念。'},{year:'2000',title:'膝伤重创',text:'经历漫长康复。'},{year:'2002',title:'王者归来',text:'世界杯决赛梅开二度。'}],honors:['2× 世界杯冠军','2× 金球奖','3× 世界足球先生'],match:'2002 世界杯决赛 · 巴西 vs 德国',fact:'他先后效力过巴塞罗那与皇家马德里，也效力过国际米兰与 AC 米兰。',image:commons('Ronaldo 2013.jpg'),credit:'Wikimedia Commons · CC BY'},
  { slug:'ronaldinho',name:'Ronaldinho',zh:'罗纳尔迪尼奥',aliases:['小罗','罗纳尔迪尼奥高乔','ronaldinho'],nation:'巴西',flag:'🇧🇷',position:'左边锋 / 前腰',years:'1998—2015',number:10,kicker:'让胜负之外的快乐重回足球',intro:'牛尾巴、no-look pass、任意球与永远的笑容，小罗的巅峰不算漫长，却定义了一代人爱上足球的方式。',clues:['我来自巴西南部。','哥哥也曾是职业球员。','我的技术动作带有强烈桑巴色彩。','我曾在伯纳乌赢得主队球迷掌声。','人们常叫我小罗。'],timeline:[{year:'1998',title:'格雷米奥首秀',text:'在家乡开启职业生涯。'},{year:'2002',title:'世界杯冠军',text:'与 3R 组合登顶。'},{year:'2003',title:'加盟巴萨',text:'带领俱乐部复兴。'},{year:'2005',title:'金球奖',text:'登上个人巅峰。'},{year:'2006',title:'欧冠冠军',text:'率巴萨再登欧洲之巅。'}],honors:['世界杯冠军','金球奖','欧冠冠军','解放者杯冠军'],match:'2005 西甲 · 皇家马德里 vs 巴塞罗那',fact:'他是少数集齐世界杯、欧冠、解放者杯和金球奖的球员。',image:commons('Ronaldinho in 2019.jpg'),credit:'Wikimedia Commons · CC licensed'},
  { slug:'thierry-henry',name:'Thierry Henry',zh:'亨利',aliases:['蒂埃里亨利','海布里之王','henry'],nation:'法国',flag:'🇫🇷',position:'中锋 / 左边锋',years:'1994—2014',number:14,kicker:'从左侧走廊划出最优雅的弧线',intro:'速度、节奏变化与远角推射是亨利的签名。他是阿森纳不败之师的攻击核心，也是英超历史最完整的前锋之一。',clues:['我是法国前锋。','我曾在意大利短暂停留。','14 号成为我的标志。','我是不败赛季球队的头号攻击手。','我的庆祝雕像站在伦敦一座球场外。'],timeline:[{year:'1994',title:'摩纳哥首秀',text:'由温格发掘。'},{year:'1998',title:'世界杯冠军',text:'成为法国队内最佳射手。'},{year:'1999',title:'加盟阿森纳',text:'从边锋转型顶级中锋。'},{year:'2004',title:'不败夺冠',text:'率队完成英超不败赛季。'},{year:'2009',title:'巴萨六冠',text:'完成俱乐部荣誉拼图。'}],honors:['世界杯冠军','欧洲杯冠军','欧冠冠军','2× 英超金靴'],match:'2004 英超 · 阿森纳 vs 利物浦',fact:'他至今仍是阿森纳队史正式比赛最佳射手。',image:commons('Thierry Henry in 2021.jpg'),credit:'Wikimedia Commons · CC BY-SA'},
  { slug:'paolo-maldini',name:'Paolo Maldini',zh:'马尔蒂尼',aliases:['保罗马尔蒂尼','maldini'],nation:'意大利',flag:'🇮🇹',position:'左后卫 / 中卫',years:'1985—2009',number:3,kicker:'防守不是破坏，而是提前完成选择',intro:'横跨四分之一个世纪的米兰队魂，既是边路标杆，也是中卫典范。位置感、节奏判断和职业寿命共同构成传奇。',clues:['我的父亲也是著名球员。','我整个职业生涯只效力一家俱乐部。','我能踢左后卫和中后卫。','3 号球衣因我暂时封存。','我参加过八次欧冠决赛。'],timeline:[{year:'1985',title:'米兰首秀',text:'16 岁登场。'},{year:'1989',title:'首夺欧冠',text:'开启欧洲王朝。'},{year:'1994',title:'双冠巅峰',text:'欧冠决赛零封巴萨。'},{year:'2003',title:'队长捧杯',text:'点球击败尤文。'},{year:'2009',title:'圣西罗告别',text:'结束 24 年一线队生涯。'}],honors:['5× 欧冠冠军','7× 意甲冠军','世界杯亚军'],match:'1994 欧冠决赛 · AC 米兰 vs 巴塞罗那',fact:'他代表 AC 米兰参加了 900 多场正式比赛。',image:commons('Paolo Maldini 2008.jpg'),credit:'Wikimedia Commons · CC licensed'},
  { slug:'kaka',name:'Kaká',zh:'卡卡',aliases:['里卡多卡卡','kaka'],nation:'巴西',flag:'🇧🇷',position:'前腰',years:'2001—2017',number:22,kicker:'大步流星穿越中场的最后一位古典巨星',intro:'卡卡的推进看似舒展，却能以极高速度直插防线。2007 年，他以欧冠淘汰赛的统治表现赢得金球奖。',clues:['我来自巴西圣保罗。','我的昵称来自弟弟的发音。','我常身穿 22 号。','我的高速长距离推进极具辨识度。','我是梅罗时代前最后一位金球奖得主。'],timeline:[{year:'2001',title:'圣保罗首秀',text:'开启职业生涯。'},{year:'2002',title:'世界杯冠军',text:'入选巴西冠军阵容。'},{year:'2003',title:'加盟米兰',text:'迅速成为进攻核心。'},{year:'2007',title:'欧洲之巅',text:'欧冠冠军并赢得金球。'},{year:'2009',title:'转会皇马',text:'以高额转会费加盟。'}],honors:['世界杯冠军','金球奖','欧冠冠军','意甲冠军'],match:'2007 欧冠半决赛 · 曼联 vs AC 米兰',fact:'2007 年欧冠他以 10 球成为赛事最佳射手。',image:commons('Kaka061115.jpg'),credit:'Wikimedia Commons · CC licensed'},
  { slug:'xavi',name:'Xavi Hernández',zh:'哈维',aliases:['哈维埃尔南德斯','xavi'],nation:'西班牙',flag:'🇪🇸',position:'中前卫',years:'1998—2019',number:6,kicker:'用扫描和传球控制比赛的时间',intro:'哈维并不依赖速度或身体，而是用持续观察、接球朝向和精确传递掌握空间。他是巴萨与西班牙黄金时代的节拍器。',clues:['我出自拉玛西亚。','我是一名身材不高的中场。','6 号是我的代表号码。','我与另一位中场搭档赢得世界杯。','退役后我回到母队执教。'],timeline:[{year:'1998',title:'巴萨首秀',text:'进入一线队。'},{year:'2008',title:'欧洲杯最佳',text:'率西班牙打破冠军荒。'},{year:'2009',title:'六冠王',text:'成为瓜迪奥拉体系核心。'},{year:'2010',title:'世界杯冠军',text:'控制西班牙中场。'},{year:'2015',title:'三冠告别',text:'队长身份捧起欧冠。'}],honors:['世界杯冠军','2× 欧洲杯冠军','4× 欧冠冠军'],match:'2011 欧冠决赛 · 巴塞罗那 vs 曼联',fact:'他在 2008 欧洲杯被评为赛事最佳球员。',image:commons('Xavi 13981129001173637176624731765221.jpg'),credit:'Wikimedia Commons · CC licensed'},
  { slug:'andres-iniesta',name:'Andrés Iniesta',zh:'伊涅斯塔',aliases:['安德烈斯伊涅斯塔','小白','iniesta'],nation:'西班牙',flag:'🇪🇸',position:'中前卫 / 前腰',years:'2002—2024',number:8,kicker:'在密集防守中找到不存在的出口',intro:'伊涅斯塔的摆脱、半转身和最后一传总在最关键的瞬间出现。2010 年世界杯决赛的进球让他永远属于西班牙足球史。',clues:['我来自西班牙小镇。','我出自拉玛西亚。','人们因我的肤色给我一个中文昵称。','我擅长油炸丸子式摆脱。','我打入世界杯决赛制胜球。'],timeline:[{year:'2002',title:'巴萨首秀',text:'进入一线队。'},{year:'2006',title:'首夺欧冠',text:'逐渐成为主力。'},{year:'2009',title:'斯坦福桥绝杀',text:'帮助球队晋级欧冠决赛。'},{year:'2010',title:'世界杯制胜球',text:'加时绝杀荷兰。'},{year:'2018',title:'告别巴萨',text:'转战日本联赛。'}],honors:['世界杯冠军','2× 欧洲杯冠军','4× 欧冠冠军'],match:'2010 世界杯决赛 · 西班牙 vs 荷兰',fact:'他的世界杯决赛进球献给已故好友达尼·哈尔克。',image:commons('Andrés Iniesta 2018.jpg'),credit:'Wikimedia Commons · CC BY-SA'},
  { slug:'gianluigi-buffon',name:'Gianluigi Buffon',zh:'布冯',aliases:['吉安路易吉布冯','buffon'],nation:'意大利',flag:'🇮🇹',position:'门将',years:'1995—2023',number:1,kicker:'二十八年站在门线前保持热爱',intro:'反应、站位、指挥与惊人的稳定性让布冯成为门将位置的时代标杆。他经历巅峰、降级与重返顶级，忠诚同样定义了他。',clues:['我是一名意大利门将。','我在 17 岁完成意甲首秀。','我的姓氏中文听起来很有福气。','我随俱乐部经历过降级。','我赢得 2006 年世界杯。'],timeline:[{year:'1995',title:'帕尔马首秀',text:'零封强大的 AC 米兰。'},{year:'1999',title:'联盟杯冠军',text:'随帕尔马夺冠。'},{year:'2001',title:'加盟尤文',text:'创造门将转会纪录。'},{year:'2006',title:'世界杯冠军',text:'赛事仅失两球。'},{year:'2023',title:'宣布退役',text:'结束 28 年职业生涯。'}],honors:['世界杯冠军','10× 意甲冠军','联盟杯冠军'],match:'2006 世界杯半决赛 · 德国 vs 意大利',fact:'他曾在尤文降入意乙后选择留队。',image:commons('Gianluigi Buffon (31784615942).jpg'),credit:'Wikimedia Commons · CC BY'},
  { slug:'manuel-neuer',name:'Manuel Neuer',zh:'诺伊尔',aliases:['曼努埃尔诺伊尔','neuer'],nation:'德国',flag:'🇩🇪',position:'门将',years:'2005—至今',number:1,kicker:'把门将活动范围扩展到整片后场',intro:'诺伊尔不仅扑救，更以出击、传球和高位覆盖成为进攻体系的一部分。“门卫”并非由他发明，却由他推向主流。',clues:['我来自德国。','我最早在鲁尔区成名。','我是一名经常冲出禁区的门将。','我长期效力拜仁慕尼黑。','2014 世界杯让我定义门卫踢法。'],timeline:[{year:'2006',title:'沙尔克首秀',text:'进入德甲赛场。'},{year:'2011',title:'加盟拜仁',text:'接过豪门一号球衣。'},{year:'2013',title:'三冠王',text:'赢得首座欧冠。'},{year:'2014',title:'世界杯冠军',text:'获得金手套奖。'},{year:'2020',title:'再夺三冠',text:'队长身份登顶欧洲。'}],honors:['世界杯冠军','2× 欧冠冠军','11× 德甲冠军'],match:'2014 世界杯 · 德国 vs 阿尔及利亚',fact:'他在高位防线身后承担的覆盖工作改变了门将评价标准。',image:commons('Manuel Neuer 8158.jpg'),credit:'Wikimedia Commons · CC BY-SA'},
  { slug:'luka-modric',name:'Luka Modrić',zh:'莫德里奇',aliases:['卢卡莫德里奇','魔笛','modric'],nation:'克罗地亚',flag:'🇭🇷',position:'中前卫',years:'2003—至今',number:10,kicker:'用外脚背和韧性让小国走到世界中央',intro:'莫德里奇以摆脱、调度、覆盖和外脚背传球连接比赛。他带领克罗地亚闯入世界杯决赛，也打破了梅罗对金球奖的长期垄断。',clues:['我来自巴尔干半岛。','童年经历过战争。','我身材不高却能覆盖整个中场。','外脚背传球是我的标志。','我在 2018 年赢得金球奖。'],timeline:[{year:'2003',title:'萨格勒布起步',text:'外租经历磨练身体。'},{year:'2008',title:'登陆热刺',text:'适应英超节奏。'},{year:'2012',title:'加盟皇马',text:'成为欧冠王朝核心。'},{year:'2018',title:'世界杯亚军',text:'赢得赛事金球奖。'},{year:'2018',title:'世界最佳',text:'赢得个人金球奖。'}],honors:['金球奖','6× 欧冠冠军','世界杯亚军'],match:'2018 世界杯半决赛 · 克罗地亚 vs 英格兰',fact:'他在 2018 年包揽世界杯金球奖、世界足球先生和金球奖。',image:'/assets/football/luka-modric.png',credit:'TheSportsDB · player cutout'},
  { slug:'mohamed-salah',name:'Mohamed Salah',zh:'萨拉赫',aliases:['穆罕默德萨拉赫','埃及梅西','salah'],nation:'埃及',flag:'🇪🇬',position:'右边锋',years:'2010—至今',number:11,kicker:'从尼罗河畔跑入英超纪录册',intro:'萨拉赫从切尔西失意离开后，在意甲重建信心，最终成为利物浦的高速进球核心，也是阿拉伯世界最具影响力的运动员之一。',clues:['我来自非洲。','我通常从右路内切使用左脚。','我在英格兰第一次尝试并不成功。','我在罗马重获认可。','我身穿利物浦 11 号。'],timeline:[{year:'2010',title:'埃及联赛首秀',text:'阿拉伯承包商起步。'},{year:'2012',title:'登陆巴塞尔',text:'进入欧洲赛场。'},{year:'2015',title:'意甲重生',text:'佛罗伦萨与罗马时期成长。'},{year:'2017',title:'加盟利物浦',text:'首季刷新英超进球纪录。'},{year:'2019',title:'欧冠冠军',text:'决赛点球首开纪录。'}],honors:['欧冠冠军','2× 英超冠军','3× 英超金靴'],match:'2018 英超 · 利物浦 vs 沃特福德',fact:'他首个利物浦赛季打入 44 球，其中英超 32 球。',image:commons('Mohamed Salah 2018.jpg'),credit:'Wikimedia Commons · CC BY-SA'},
  { slug:'kylian-mbappe',name:'Kylian Mbappé',zh:'姆巴佩',aliases:['基利安姆巴佩','mbappe'],nation:'法国',flag:'🇫🇷',position:'中锋 / 左边锋',years:'2015—至今',number:10,kicker:'把防线身后的每一米变成危险',intro:'爆发启动、无球前插和高效终结使姆巴佩很早就站上世界舞台。他在两届世界杯决赛中打入四球，仍在书写上限。',clues:['我出生在巴黎郊区。','我的父亲是足球教练。','速度是我的第一标签。','我未满 20 岁便赢得世界杯。','我在一场世界杯决赛上演帽子戏法。'],timeline:[{year:'2015',title:'摩纳哥首秀',text:'刷新俱乐部最年轻纪录。'},{year:'2017',title:'欧冠突破',text:'帮助摩纳哥打入四强。'},{year:'2018',title:'世界杯冠军',text:'决赛进球。'},{year:'2022',title:'决赛帽子戏法',text:'赢得世界杯金靴。'},{year:'2024',title:'加盟皇马',text:'开启西甲生涯。'}],honors:['世界杯冠军','世界杯金靴','多次法甲冠军'],match:'2022 世界杯决赛 · 阿根廷 vs 法国',fact:'他是继赫斯特之后第二位在男足世界杯决赛戴帽的球员。',image:commons('Kylian Mbappé 2019.jpg'),credit:'Wikimedia Commons · CC BY'},
  { slug:'son-heung-min',name:'Son Heung-min',zh:'孙兴慜',aliases:['孙兴民','son','son heungmin'],nation:'韩国',flag:'🇰🇷',position:'左边锋 / 中锋',years:'2010—至今',number:7,kicker:'亚洲攻击手在欧洲最高舞台的答案',intro:'双足均衡、纵向速度与快速终结让孙兴慜成为英超顶级攻击手。他以无点球金靴证明亚洲球员同样可以定义世界级。',clues:['我来自东亚。','父亲对我的基本功训练非常严格。','我在德国开启欧洲职业生涯。','我左右脚终结都很出色。','我是首位获得英超金靴的亚洲球员。'],timeline:[{year:'2010',title:'汉堡首秀',text:'在德甲开启职业生涯。'},{year:'2013',title:'加盟勒沃库森',text:'继续成长为主力。'},{year:'2015',title:'登陆英超',text:'加盟托特纳姆热刺。'},{year:'2019',title:'欧冠决赛',text:'随队创造队史成绩。'},{year:'2022',title:'英超金靴',text:'23 球且无点球。'}],honors:['英超金靴','普斯卡什奖','亚运会冠军'],match:'2019 英超 · 热刺 vs 伯恩利',fact:'他获得普斯卡什奖的进球来自一次贯穿大半场的长途奔袭。',image:commons('Team Korea Russia WorldCup 02 (cropped).png'),credit:'Wikimedia Commons · CC licensed'}
]

export const normalize = (value: string) => value.toLowerCase().replace(/[\s·.\-_']/g, '')
export const accepts = (player: Player, input: string) => [player.zh, player.name, ...player.aliases].some(name => normalize(name) === normalize(input))
